name: Continuous Deployment

# This CD workflow is triggered only when the CI workflow completes successfully
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest # Specifies that the job should run on the latest Ubuntu runner

    steps:
      # Checkout the code in the GitHub repository
      - uses: actions/checkout@v4

      # Set up .NET 7
      - name: Set up .NET 7
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Publish the project
      - name: Publish project
        run: dotnet publish --configuration Release --no-restore --output publish

      # Package the application for deployment
      - name: Package application
        run: |
          cd publish
          zip -r ../conway.api.zip .
          
      # Set up the specified Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install AWS Command Line Interface for interacting with AWS services
      - name: Install AWS CLI
        run: pip install awscli

      # Configure AWS credentials for access to AWS services
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Upload the ZIP file to the specified S3 bucket
      - name: Upload ZIP to S3
        run: |
          aws s3 cp conway.api.zip s3://${{ secrets.S3_KEY }}/conway.api-${{ github.sha }}.zip

      # Deploy the application to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name conway-api \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=${{ secrets.S3_KEY }},S3Key=conway.api-${{ github.sha }}.zip
          aws elasticbeanstalk update-environment \
            --environment-name conway-api-env \
            --version-label ${{ github.sha }}
